language: erlang
otp_release:
  - R16B03
  - R15B03
notifications:
  slack:
    secure: OIl/wglitmlcvzoHvu9hQCjfcAOQ57Kkxp/+e1IsbU4Oz6Q3NHy3j+fsBAkP/KWWDM03c/0Onqsiua76sztfadoJXpZQsbiMLwUPR2clMgGOY3HIrPF4XMzT72tXQRl8/M1o885X+Eejdc2DE3F4h/iVyS45GYPfBXtnzla+hRg=
