name: Erlang CI

on:
  push:
    branches: [ nhse-develop-3.4 ]
  pull_request:
    branches: [ nhse-develop-3.4 ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        otp:
          - "26"
          - "24.3"

    container:
      image: erlang:${{ matrix.otp }}

    steps:
      - uses: lukka/get-cmake@latest
      - uses: actions/checkout@v2
      - name: Compile
        run: ./rebar3 compile
      - name: Run xref and dialyzer
        run: ./rebar3 do xref, dialyzer
      - name: Run eunit
        run: ./rebar3 as gha do eunit
